// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHMxX61XWzu2uPYc5w2iljMArmgKFajI',
    appId: '1:334945658513:web:1df61e51bd1f20f6770130',
    messagingSenderId: '334945658513',
    projectId: 'itts-aplikasi-mobile',
    authDomain: 'itts-aplikasi-mobile.firebaseapp.com',
    storageBucket: 'itts-aplikasi-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NICaKvxucpWuQZfHTSC1FdrXgRV6Cmk',
    appId: '1:334945658513:android:7e3f010de4583b6b770130',
    messagingSenderId: '334945658513',
    projectId: 'itts-aplikasi-mobile',
    storageBucket: 'itts-aplikasi-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBij9s1JnRRrSGmwJ6MJv0TqU5w33IT3_0',
    appId: '1:334945658513:ios:41112781529e7010770130',
    messagingSenderId: '334945658513',
    projectId: 'itts-aplikasi-mobile',
    storageBucket: 'itts-aplikasi-mobile.appspot.com',
    iosBundleId: 'com.example.appRentalMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBij9s1JnRRrSGmwJ6MJv0TqU5w33IT3_0',
    appId: '1:334945658513:ios:599d423fd9601271770130',
    messagingSenderId: '334945658513',
    projectId: 'itts-aplikasi-mobile',
    storageBucket: 'itts-aplikasi-mobile.appspot.com',
    iosBundleId: 'com.example.appRentalMobil.RunnerTests',
  );
}
