// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfaPX9yGnPfAleJUw1OM67Opt_UFXHXWE',
    appId: '1:24543238125:web:8f09cb005c69cce4f979e4',
    messagingSenderId: '24543238125',
    projectId: 'rent-car-711b1',
    authDomain: 'rent-car-711b1.firebaseapp.com',
    storageBucket: 'rent-car-711b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPKTsSYrhw-hTTo5O-VmM9F9xPDpSExs',
    appId: '1:24543238125:android:043306d399bb8b83f979e4',
    messagingSenderId: '24543238125',
    projectId: 'rent-car-711b1',
    storageBucket: 'rent-car-711b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYx0hbCsP6R_Bx33TJrJ4by9y-M9tSzU',
    appId: '1:24543238125:ios:a527ec4efcbfe783f979e4',
    messagingSenderId: '24543238125',
    projectId: 'rent-car-711b1',
    storageBucket: 'rent-car-711b1.appspot.com',
    iosBundleId: 'com.example.appRentalMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYx0hbCsP6R_Bx33TJrJ4by9y-M9tSzU',
    appId: '1:24543238125:ios:a7093a354d2874f5f979e4',
    messagingSenderId: '24543238125',
    projectId: 'rent-car-711b1',
    storageBucket: 'rent-car-711b1.appspot.com',
    iosBundleId: 'com.example.appRentalMobil.RunnerTests',
  );
}
